#version: "2"
services: 
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: always
    volumes:
      - ./db/mongod.conf:/etc/mongod.conf
      #- ./logs:/var/log/mongod/
      #- ./db:/var/lib/mongodb
      #- ./mongod.service:/lib/systemd/system/mongod.service
    ports:
      - "27017:27017"

  app:
    container_name: app
    restart: always
    build: ./web
    ports:
      - "3000:3000"
    # links:
    #   - mongo
    environment: 
      - DB_HOST=mongodb://mongo:27017/posts
    depends_on:
      - mongo